id: toi_news_summary
namespace: company.team
description: |
  Automated workflow to fetch and summarize Times of India RSS feeds using Gemini 2.0 Flash Lite.
  Saves summaries and links in category-wise timestamped folders.

inputs:
  - id: categories
    type: STRING
    defaults: "world,technology"
  - id: gemini_api_key
    type: STRING
    required: true
  - id: prompt
    type: STRING
    defaults: "Summarize these news articles in 3 short bullet points."

tasks:
  - id: start_log
    type: io.kestra.plugin.core.log.Log
    message: |
       Starting TOI Summarization Workflow
       {{ now() }}
       Categories: {{ inputs.categories }}

  - id: fetch_feeds
    type: io.kestra.plugin.scripts.python.Script
    runner: PROCESS
    containerImage: python:3.11-slim
    beforeCommands:
      - apt-get update && apt-get install -y curl ca-certificates && update-ca-certificates
      - pip install feedparser requests
    env:
      CATEGORIES: "{{ inputs.categories }}"
    inputFiles:
      fetch_feeds.py: "{{ read('fetch_feeds.py') }}"
    script: |
      import fetch_feeds
      fetch_feeds.main()
    outputFiles:
      - "toi_rss_output.json"

  - id: summarize_feeds
    type: io.kestra.plugin.scripts.python.Script
    runner: PROCESS
    containerImage: python:3.11-slim
    beforeCommands:
      - pip install requests psycopg2-binary
    env:
      GEMINI_API_KEY: "{{ inputs.gemini_api_key }}"
      CUSTOM_PROMPT: "{{ inputs.prompt }}"
      DATABASE_URL: "postgresql://kestra:k3str4@host.docker.internal:5432/kestra"
    inputFiles:
      summarize_feeds.py: "{{ read('summarize_feeds.py') }}"
      toi_rss_output.json: "{{ outputs.fetch_feeds.outputFiles['toi_rss_output.json'] }}"
    script: |
      import summarize_feeds
      summarize_feeds.main()
    outputFiles:
      - "**/*.txt"
      - "**/*.json"
      - "all_processed_links.json"

  - id: show_summary
    type: io.kestra.plugin.core.log.Log
    message: |
       Summarization completed successfully!
       Categories processed: {{ inputs.categories }}
       {{ now() }}
       Output saved in category folders.


triggers:
  - id: hourly_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"
